import Editor from "./editor.js";
import Keyboard from "./keyboard.js";

const platform = (navigator.platform.includes("Mac")) ? "mac" : "basic";
console.log(platform);

const keyboard = new Keyboard();
keyboard.add();


const basicLayout = [
    {
        "row":0,
        "content":"`",
        "modifier":"~",
        "type":"tilda-button",
    },
    {
        "row":0,
        "content":"1",
        "modifier":"!",
        "type":"basic",
    },
    {
        "row":0,
        "content":"2",
        "modifier":"@",
        "type":"basic",
    },
    {
        "row":0,
        "content":"3",
        "modifier":"#",
        "type":"basic",
    },
    {
        "row":0,
        "content":"4",
        "modifier":"$",
        "type":"basic",
    },
    {
        "row":0,
        "content":"5",
        "modifier":"%",
        "type":"basic",
    },
    {
        "row":0,
        "content":"6",
        "modifier":":",
        "type":"basic",
    },
    {
        "row":0,
        "content":"7",
        "modifier":"?",
        "type":"basic",
    },
    {
        "row":0,
        "content":"8",
        "modifier":"*",
        "type":"basic",
    },
    {
        "row":0,
        "content":"9",
        "modifier":"(",
        "type":"basic",
    },
    {
        "row":0,
        "content":"0",
        "modifier":")",
        "type":"basic",
    },
    {
        "row":0,
        "content":"-",
        "modifier":"_",
        "type":"basic",
    },
    {
        "row":0,
        "content":"=",
        "modifier":"+",
        "type":"basic",
    },
    {
        "row":0,
        "content":"Backspace",
        "modifier":"",
        "type":"backspace-button",
    },

    // Row 1
    {
        "row":1,
        "content":"Tab",
        "modifier":"",
        "type":"tab-button",
    },
    {
        "row":1,
        "content":"Q",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"W",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"E",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"R",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"T",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"Y",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"U",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"I",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"O",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"P",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"[",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"]",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":1,
        "content":"\\",
        "modifier":"/",
        "type":"basic",
    },
    {
        "row":1,
        "content":"Del",
        "modifier":"",
        "type":"meta-basic-button",
    },
    {
        "row":2,
        "content":"Caps Lock",
        "modifier":"",
        "type":"meta-button",
    },

    {
        "row":2,
        "content":"A",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":"S",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":"D",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":"F",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":"G",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":"H",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":"J",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":"K",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":"L",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":";",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":"'",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":2,
        "content":"Enter",
        "modifier":"",
        "type":"enter-button",
    },
    {
        "row":3,
        "content":"Shift",
        "modifier":"",
        "type":"meta-button",
    },
    {
        "row":3,
        "content":"\\",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":"Z",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":"X",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":"C",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":"V",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":"B",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":"N",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":"M",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":".",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":",",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":"/",
        "modifier":"",
        "type":"basic",
    },
    {
        "row":3,
        "content":"↑",
        "modifier":"",
        "type":"meta-basic-button",
    },
    {
        "row":3,
        "content":"Shift",
        "modifier":"",
        "type":"meta-basic-button",
    },
    {
        "row":4,
        "content":"Ctrl",
        "modifier":"",
        "type":"ctrl-button",
    },
    {
        "row":4,
        "content":"Win",
        "modifier":"",
        "type":"meta-basic-button",
    },
    {
        "row":4,
        "content":"Alt",
        "modifier":"",
        "type":"meta-basic-button",
    },
    {
        "row":4,
        "content":"",
        "modifier":"",
        "type":"space-button",
    },
    {
        "row":4,
        "content":"Alt",
        "modifier":"",
        "type":"meta-basic-button",
    },
    {
        "row":4,
        "content":"Ctrl",
        "modifier":"",
        "type":"ctrl-button",
    },
    {
        "row":4,
        "content":"←",
        "modifier":"",
        "type":"meta-basic-button",
    },
    {
        "row":4,
        "content":"↓",
        "modifier":"",
        "type":"meta-basic-button",
    },
    {
        "row":4,
        "content":"→",
        "modifier":"",
        "type":"meta-basic-button",
    },
]

for(let {row, content, modifier, type} of basicLayout){
    keyboard.addButton(row, content, modifier, type);
}